In [62]:
import sklearn as sk
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.externals.six import StringIO

import pydotplus
import numpy as np

In [63]:
#incase 
#filepath = "/Users/danemorgan/Documents/DataScience/CSVs/IRIS.csv"

iris = load_iris()

#print(iris.feature_names)
#print(iris.target_names)
#print(iris.data[0])
#print(iris.target[0])
#Print out whole Data Set
#for i in range(len(iris.target)):
#   print("Example{%d}: label{%s}, features{%s}" % (i, iris.target[i], iris.data[i]))

In [64]:
#testing data -- examples to put asign to test classifier algo accuracy
test_idx = [0,50,100]
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

#TRAINING DATA
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [65]:
#Classifier here
clf = tree.DecisionTreeClassifier()
#find patterns in data from training sets
clf.fit(train_data, train_target)

print(test_target)

[0 1 2]


In [66]:
print(clf.predict(test_data))
#it works!

[0 1 2]


In [76]:
#Visualization code here
dot_data = StringIO()
tree.export_graphviz(clf,out_file=dot_data,
                     feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True, rounded=True,
                    impurity=False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

True

In [77]:
print(test_data[1],test_target[1])
print(iris.feature_names, iris.target_names)

[7.  3.2 4.7 1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
