In [23]:
# make sure to install the modules you need
# pip3 install sklearn matplotlib numpy scipy pydotplus
from sklearn.datasets import load_iris
from sklearn import tree
from sklearn.externals.six import StringIO
import graphviz
import pydotplus
import numpy as np

In [24]:
iris = load_iris()
#print(iris) # 150 pieces of data, 5 attributes each

In [25]:
#print(iris.target_names)

#print(iris.target[0]) # 0 = setosa, 1 = versacolor, 2 = virginica

#print(iris.feature_names)



In [38]:
# We'll come back to these three
print(iris.data[0])
print(iris.data[50])
print(iris.data[100])

[5.1 3.5 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.3 3.3 6.  2.5]


In [27]:
#Print out whole Data Set
for i in range(len(iris.target)):
   print("Example{%d}: label{%s}, features{%s}" % (i, iris.target[i], iris.data[i]))

Example{0}: label{0}, features{[5.1 3.5 1.4 0.2]}
Example{1}: label{0}, features{[4.9 3.  1.4 0.2]}
Example{2}: label{0}, features{[4.7 3.2 1.3 0.2]}
Example{3}: label{0}, features{[4.6 3.1 1.5 0.2]}
Example{4}: label{0}, features{[5.  3.6 1.4 0.2]}
Example{5}: label{0}, features{[5.4 3.9 1.7 0.4]}
Example{6}: label{0}, features{[4.6 3.4 1.4 0.3]}
Example{7}: label{0}, features{[5.  3.4 1.5 0.2]}
Example{8}: label{0}, features{[4.4 2.9 1.4 0.2]}
Example{9}: label{0}, features{[4.9 3.1 1.5 0.1]}
Example{10}: label{0}, features{[5.4 3.7 1.5 0.2]}
Example{11}: label{0}, features{[4.8 3.4 1.6 0.2]}
Example{12}: label{0}, features{[4.8 3.  1.4 0.1]}
Example{13}: label{0}, features{[4.3 3.  1.1 0.1]}
Example{14}: label{0}, features{[5.8 4.  1.2 0.2]}
Example{15}: label{0}, features{[5.7 4.4 1.5 0.4]}
Example{16}: label{0}, features{[5.4 3.9 1.3 0.4]}
Example{17}: label{0}, features{[5.1 3.5 1.4 0.3]}
Example{18}: label{0}, features{[5.7 3.8 1.7 0.3]}
Example{19}: label{0}, features{[5.1 3.8 

In [5]:
#training data
# taking the target data out so we don't know which species is assigned to each piece of data
train_target = np.delete(iris.target, test_idx)
#print(train_target)

In [ ]:
train_data = np.delete(iris.data, test_idx, axis=0)
#print(train_data)

In [16]:
#testing data -- examples to put assign to test classifier algo accuracy
test_idx = [0,50,100]
test_target = iris.target[test_idx]
print("Test Target", test_target)

Test Target [0 1 2]


In [17]:
test_data = iris.data[test_idx]
print("Test Data", test_data)

Test Data [[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]


In [7]:
#Classifier, telling the minions how to decide which iris is a sentosa, virginica, or a versicolor
clf = tree.DecisionTreeClassifier()


[0 1 2]


In [18]:
#This is where the magic happens!
#find patterns in data from training sets
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [33]:
print("Prediction: ",clf.predict(test_data))
#it works!

Prediction [0 1 2]


In [37]:
print(test_data)
print(iris.target[0])
print(iris.target[50])
print(iris.target[100])

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]]
0
1
2


In [34]:
#Visualization  here
dot_data = StringIO()
tree.export_graphviz(clf,out_file=dot_data,
                     feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True, rounded=True,
                    impurity=False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

True

In [35]:
print(test_data[1],test_target[1])
print(iris.target_names, iris.feature_names)

[7.  3.2 4.7 1.4] 1
['setosa' 'versicolor' 'virginica'] ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
